services:
  postgres:
    image: postgres:13
    hostname: postgres
    container_name: nestjs-template
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - database.env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nestjs-template
